name: Generate RSS Feed

on:
  push:
    branches:
      - stage  # Adjust the branch name if needed

jobs:
  generate_rss_feed:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8  # Use the appropriate Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install beautifulsoup4 feedgen pytz requests

      - name: Generate RSS Feed and Save
        run: |
          python generate_rss.py
          mv blog_rss_feed.xml $GITHUB_WORKSPACE/blog_rss_feed.xml
